# Main Menu
[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

[[main]]
  name = "Background"
  pageRef = "background"
  weight = 30

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 40
